$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: used-cars-training-pipeline
experiment_name: used-cars-training-experiment
description: Pipeline to prepare data, train model using sweep, and register model

inputs:
  raw_data:
    type: uri_file
    path: azureml:used-cars-data@latest

outputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  model_info_output_path:
    type: uri_file

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    type: command
    name: prep_data
    display_name: prepare-data
    code: ../../../data-science/src
    command: >-
      python prep.py  
      --raw_data ${{inputs.raw_data}} 
      --train_data ${{outputs.train_data}}
      --test_data ${{outputs.test_data}} 
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    type: sweep
    name: sweep_model
    display_name: sweep-random-forest
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output:
        type: mlflow_model
    sampling_algorithm: random
    trial: ./train.yml  # references your valid train component
    search_space:
      n_estimators:
        type: choice
        values: [10, 20, 30, 50]
      max_depth:
        type: choice
        values: [3, 5, 10, 15]
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    type: command
    name: register_model
    display_name: register-trained-model
    code: ../../../data-science/src
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_name: "used_cars_price_prediction_model"
      model_path: ${{parent.jobs.sweep_step.outputs.model_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}
